# Carrega as definições (exchange, queue, binding) automaticamente na inicialização
load_definitions = /etc/rabbitmq/definitions.json

# Habilita o plugin de management (UI)
management.load_definitions = /etc/rabbitmq/definitions.json
